# Generated by Django 5.2.7 on 2025-11-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Actividades',
                
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('orden', models.CharField(max_length=50)),
                ('maquina', models.CharField(max_length=50)),
                ('molde', models.CharField(max_length=50)),
                ('parte_actual', models.CharField(max_length=50)),
                ('parte_entrante', models.CharField(max_length=50)),
                ('defecto1', models.CharField(max_length=100)),
                ('cavidad1', models.CharField(max_length=50)),
                ('defecto2', models.CharField(max_length=100)),
                ('cavidad2', models.CharField(max_length=50)),
                ('defecto3', models.CharField(max_length=100)),
                ('cavidad3', models.CharField(max_length=50)),
                ('tecnico1', models.CharField(max_length=50)),
                ('tecnico2', models.CharField(max_length=50)),
                ('tecnico3', models.CharField(max_length=50)),
                ('tecnico4', models.CharField(max_length=50)),
                ('tecnico5', models.CharField(max_length=50)),
                ('tecnico6', models.CharField(max_length=50)),
                ('tecnico7', models.CharField(max_length=50)),
                ('tecnico8', models.CharField(max_length=50)),
                ('tecnico9', models.CharField(max_length=50)),
                ('lider1', models.CharField(max_length=50)),
                ('lider2', models.CharField(max_length=50)),
                ('fecha_paro', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.FloatField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('retorno', models.CharField(max_length=50)),
                ('estatus', models.CharField(max_length=50)),
                ('info_retorno', models.CharField(max_length=100)),
                ('defecto_retorno', models.CharField(max_length=100)),
                ('lider_retorno', models.CharField(max_length=50)),
                ('tecnico_retorno', models.CharField(max_length=50)),
                ('estatus2', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=50)),
                ('prioridad', models.CharField(max_length=50)),
                ('comentarios', models.TextField()),
            ],
            options={
                'db_table': 'bitacora_bitacora',
                
            },
        ),
        migrations.CreateModel(
            name='Defectos',
            fields=[
                ('id_defecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_defecto', models.TextField(blank=True, null=True)),
                ('main_activity', models.TextField(blank=True, db_column='Main_activity', null=True)),
            ],
            options={
                'db_table': 'Defectos',
                
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('numero_estatus', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Estatus',
                
            },
        ),
        migrations.CreateModel(
            name='Lideres',
            fields=[
                ('id_lider', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Lideres',
                
            },
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id_maquinas', models.AutoField(db_column='id_Maquinas', primary_key=True, serialize=False)),
                ('wc', models.TextField(blank=True, db_column='WC', null=True)),
                ('mn', models.TextField(blank=True, db_column='MN', null=True)),
                ('wc2', models.TextField(blank=True, db_column='WC2', null=True)),
            ],
            options={
                'db_table': 'Maquinas',
                
            },
        ),
        migrations.CreateModel(
            name='Moldes',
            fields=[
                ('id_molde', models.AutoField(db_column='id_Molde', primary_key=True, serialize=False)),
                ('numero_molde', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'Moldes',
                
            },
        ),
        migrations.CreateModel(
            name='Moldmakers',
            fields=[
                ('id_mold_m', models.AutoField(db_column='id_Mold_m', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, db_column='Nombre', null=True)),
            ],
            options={
                'db_table': 'MoldMakers',
                
            },
        ),
        migrations.CreateModel(
            name='NumerosDeParte',
            fields=[
                ('id_np', models.AutoField(primary_key=True, serialize=False)),
                ('numero_parte', models.TextField(blank=True, null=True)),
                ('terminacion', models.TextField(blank=True, null=True)),
                ('inicio', models.TextField(blank=True, null=True)),
                ('number_part', models.TextField(blank=True, null=True)),
                ('junto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Numeros_de_parte',
               
            },
        ),
        migrations.CreateModel(
            name='Retorno',
            fields=[
                ('id_retorno', models.AutoField(primary_key=True, serialize=False)),
                ('retorno_opcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Retorno',
                
            },
        ),
        migrations.CreateModel(
            name='RetornoInfo',
            fields=[
                ('id_retorno_info', models.AutoField(db_column='id_Retorno_info', primary_key=True, serialize=False)),
                ('info_retorno', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Retorno_info',
                
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id_semana', models.AutoField(primary_key=True, serialize=False)),
                ('semana_natural', models.TextField(blank=True, null=True)),
                ('semana_fiscal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Semana',
                
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id_zona', models.AutoField(db_column='id_Zona', primary_key=True, serialize=False)),
                ('zona', models.TextField(blank=True, db_column='Zona', null=True)),
                ('wc', models.TextField(blank=True, db_column='WC', null=True)),
                ('mn', models.TextField(blank=True, db_column='MN', null=True)),
            ],
            options={
                'db_table': 'Zonas',
               
            },
        ),
    ]
