# Generated by Django 5.2.8 on 2026-01-06 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_defecto', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Defecto',
                'verbose_name_plural': 'Defectos',
            },
        ),
        migrations.CreateModel(
            name='Lideres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('id_empleado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Líder',
                'verbose_name_plural': 'Líderes',
            },
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='Moldes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Molde',
                'verbose_name_plural': 'Moldes',
            },
        ),
        migrations.CreateModel(
            name='Moldmakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('num_empleado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Técnico (Moldmaker)',
                'verbose_name_plural': 'Técnicos (Moldmakers)',
            },
        ),
        migrations.CreateModel(
            name='OrdenSAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_center', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
                ('tipo_mntn', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_retorno', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_retorno', models.TextField(blank=True, null=True)),
                ('orden_retorno_ref', models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True)),
                ('maquina', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lideradas', to=settings.AUTH_USER_MODEL)),
                ('molde', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_cho', to='Moldeo.moldes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenMCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
                ('tipo_mntn', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_retorno', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_retorno', models.TextField(blank=True, null=True)),
                ('orden_retorno_ref', models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True)),
                ('maquina', models.CharField(blank=True, max_length=50, null=True)),
                ('defecto_sap', models.CharField(max_length=100)),
                ('defecto_real', models.TextField()),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lideradas', to=settings.AUTH_USER_MODEL)),
                ('molde', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mcm', to='Moldeo.moldes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPREP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
                ('tipo_mntn', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_retorno', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_retorno', models.TextField(blank=True, null=True)),
                ('orden_retorno_ref', models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True)),
                ('maquina', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lideradas', to=settings.AUTH_USER_MODEL)),
                ('molde', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_prep', to='Moldeo.moldes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenTPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
                ('tipo_mntn', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_retorno', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones_retorno', models.TextField(blank=True, null=True)),
                ('orden_retorno_ref', models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True)),
                ('maquina', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lideradas', to=settings.AUTH_USER_MODEL)),
                ('molde', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_tpm', to='Moldeo.moldes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionUniversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('nombre_tecnico', models.CharField(max_length=200)),
                ('mesa', models.CharField(blank=True, max_length=50, null=True)),
                ('cavidad', models.CharField(blank=True, max_length=255, null=True)),
                ('circuito', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_sistema', models.CharField(default='Estandar', max_length=50)),
                ('defecto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('detalles_json', models.TextField(blank=True, default='[]', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='Moldeo_asig_content_86b473_idx')],
            },
        ),
    ]
