# Generated by Django 5.2.8 on 2026-01-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldes',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moldes_asignados', to='Moldeo.maquinas'),
        ),
    ]
