# Generated by Django 5.2.7 on 2025-11-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bitacora',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='defectos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estatus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lideres',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='maquinas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moldes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moldmakers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='numerosdeparte',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='retorno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='retornoinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='semana',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='zonas',
            options={'managed': False},
        ),
    ]
