# Generated by Django 5.2.8 on 2025-11-13 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0002_ordencho_ordenmcm_ordentpm_itemcavidad_itemmesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencho',
            name='defecto_real',
        ),
        migrations.RemoveField(
            model_name='ordencho',
            name='defecto_sap',
        ),
        migrations.RemoveField(
            model_name='ordencho',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ordenmcm',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ordentpm',
            name='defecto_real',
        ),
        migrations.RemoveField(
            model_name='ordentpm',
            name='defecto_sap',
        ),
        migrations.RemoveField(
            model_name='ordentpm',
            name='fecha',
        ),
        migrations.AddField(
            model_name='ordencho',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencho',
            name='molde',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='molde',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
