# Generated by Django 5.2.8 on 2026-01-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0002_moldes_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.RenameField(
            model_name='moldes',
            old_name='cliente',
            new_name='proyecto',
        ),
        migrations.RemoveField(
            model_name='defectos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='defectos',
            name='nombre_defecto',
        ),
        migrations.AddField(
            model_name='defectos',
            name='actividad_asociada',
            field=models.TextField(blank=True, null=True, verbose_name='Actividad Asociada'),
        ),
        migrations.AddField(
            model_name='defectos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defectos',
            name='categoria_ingles',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoría (Inglés)'),
        ),
        migrations.AddField(
            model_name='defectos',
            name='codigo_estatus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Estatus'),
        ),
        migrations.AddField(
            model_name='defectos',
            name='nombre',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moldes',
            name='cavidades',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='moldes',
            name='molde_sap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Molde SAP'),
        ),
        migrations.AlterField(
            model_name='moldes',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Molde'),
        ),
        migrations.AlterField(
            model_name='moldes',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moldes', to='Moldeo.maquina'),
        ),
        migrations.CreateModel(
            name='NumeroParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(max_length=100)),
                ('molde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_parte', to='Moldeo.moldes')),
            ],
            options={
                'verbose_name': 'Número de Parte',
                'verbose_name_plural': 'Números de Parte',
            },
        ),
        migrations.DeleteModel(
            name='Maquinas',
        ),
    ]
