# Generated by Django 5.2.8 on 2026-01-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0003_maquina_rename_cliente_moldes_proyecto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maquina',
            new_name='Maquinas',
        ),
        migrations.RenameModel(
            old_name='NumeroParte',
            new_name='NumerosParte',
        ),
    ]
