# Generated by Django 5.2.8 on 2025-11-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0003_remove_ordencho_defecto_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ordencho',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20),
        ),
    ]
