# Generated by Django 5.2.8 on 2025-11-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0004_ordencho_comentarios_ordencho_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPREP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('molde', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('material', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ordenmcm',
            name='defecto_real',
        ),
        migrations.RemoveField(
            model_name='ordenmcm',
            name='defecto_sap',
        ),
    ]
