# Generated by Django 5.2.8 on 2026-01-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0004_rename_maquina_maquinas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectos',
            old_name='nombre',
            new_name='nombre_defecto',
        ),
    ]
