# Generated by Django 5.2.8 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0005_ordenprep_remove_ordenmcm_defecto_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmcm',
            name='defecto_real',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='defecto_sap',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
