# Generated by Django 5.2.8 on 2026-01-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0005_rename_nombre_defectos_nombre_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='parte_entrante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordencho',
            name='parte_saliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
