# Generated by Django 5.2.8 on 2026-01-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0006_ordencho_parte_entrante_ordencho_parte_saliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='defecto_sap',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='defecto_sap',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='defecto_sap',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
