# Generated by Django 5.2.8 on 2025-11-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0007_itemcircuito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencho',
            name='molde',
        ),
        migrations.RemoveField(
            model_name='ordencho',
            name='tipo_cuchilla',
        ),
        migrations.RemoveField(
            model_name='ordenmcm',
            name='molde',
        ),
        migrations.RemoveField(
            model_name='ordenprep',
            name='material',
        ),
        migrations.RemoveField(
            model_name='ordenprep',
            name='molde',
        ),
        migrations.RemoveField(
            model_name='ordentpm',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='ordentpm',
            name='molde',
        ),
    ]
