# Generated by Django 5.2.8 on 2026-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0007_ordencho_defecto_sap_ordenprep_defecto_sap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('verde', 'Verde'), ('roja', 'Roja')], default='verde', max_length=10),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('verde', 'Verde'), ('roja', 'Roja')], default='verde', max_length=10),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('verde', 'Verde'), ('roja', 'Roja')], default='verde', max_length=10),
        ),
    ]
