# Generated by Django 5.2.8 on 2025-11-20 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0008_remove_ordencho_molde_remove_ordencho_tipo_cuchilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='molde',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_cho', to='Moldeo.moldes'),
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='molde',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mcm', to='Moldeo.moldes'),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='molde',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_prep', to='Moldeo.moldes'),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='molde',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_tpm', to='Moldeo.moldes'),
        ),
    ]
