# Generated by Django 5.2.8 on 2026-01-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0008_ordencho_tipo_tarjeta_ordenprep_tipo_tarjeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaTPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubZonaTPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requiere_detalles', models.BooleanField(default=False, help_text='Marcar si esta subzona pide módulo, cavidad, etc.')),
                ('activo', models.BooleanField(default=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subzonas', to='Moldeo.zonatpm')),
            ],
        ),
    ]
