# Generated by Django 5.2.8 on 2025-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0009_ordencho_molde_ordenmcm_molde_ordenprep_molde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmcm',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
