# Generated by Django 5.2.8 on 2026-01-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0009_actividadtpm_zonatpm_subzonatpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('color', models.CharField(default='gray', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='actividadtpm',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subzonatpm',
            name='requiere_detalles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zonatpm',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
