# Generated by Django 5.2.8 on 2025-11-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0010_ordenmcm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='tipo_mntn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='tipo_mntn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='tipo_mntn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='tipo_mntn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
