# Generated by Django 5.2.8 on 2026-01-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0010_estatusorden_alter_actividadtpm_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatusorden',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='estatusorden',
            name='color',
        ),
        migrations.AddField(
            model_name='estatusorden',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
