# Generated by Django 5.2.8 on 2026-01-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0011_remove_estatusorden_codigo_remove_estatusorden_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensap',
            name='system_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
