# Generated by Django 5.2.8 on 2025-11-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0011_ordencho_tipo_mntn_ordenmcm_tipo_mntn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencho',
            name='tipo_mntn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenmcm',
            name='tipo_mntn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenprep',
            name='tipo_mntn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordentpm',
            name='tipo_mntn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
