# Generated by Django 5.2.8 on 2026-01-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0012_ordensap_system_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moldmakers',
            options={},
        ),
        migrations.AddField(
            model_name='moldmakers',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
