# Generated by Django 5.2.8 on 2025-11-21 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0012_alter_ordencho_tipo_mntn_alter_ordenmcm_tipo_mntn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='duracion_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordencho',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='duracion_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='duracion_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='duracion_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
