# Generated by Django 5.2.8 on 2025-11-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0013_ordencho_duracion_segundos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenSAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_center', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
