# Generated by Django 5.2.8 on 2026-01-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0013_alter_moldmakers_options_moldmakers_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPREP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
