# Generated by Django 5.2.8 on 2026-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0014_actividadprep'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='detalle_entrante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordencho',
            name='detalle_saliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
