# Generated by Django 5.2.8 on 2025-12-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0015_itemtecnico_activo_itemtecnico_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
