# Generated by Django 5.2.8 on 2025-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0017_itemdefecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
