# Generated by Django 5.2.8 on 2025-12-09 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0018_ordencho_status_ordenprep_status_ordentpm_status'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcircuito',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='itemdefecto',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='itemmesa',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='itemtecnico',
            name='content_type',
        ),
        migrations.CreateModel(
            name='AsignacionUniversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('nombre_tecnico', models.CharField(max_length=200)),
                ('mesa', models.CharField(blank=True, max_length=50, null=True)),
                ('cavidad', models.CharField(blank=True, max_length=50, null=True)),
                ('circuito', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemCavidad',
        ),
        migrations.DeleteModel(
            name='ItemCircuito',
        ),
        migrations.DeleteModel(
            name='ItemDefecto',
        ),
        migrations.DeleteModel(
            name='ItemMesa',
        ),
        migrations.DeleteModel(
            name='ItemTecnico',
        ),
        migrations.AddIndex(
            model_name='asignacionuniversal',
            index=models.Index(fields=['content_type', 'object_id'], name='Moldeo_asig_content_86b473_idx'),
        ),
    ]
