# Generated by Django 5.2.8 on 2025-12-09 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0019_remove_itemcircuito_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionuniversal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asignacionuniversal',
            name='defecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asignacionuniversal',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionuniversal',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
