# Generated by Django 5.2.8 on 2025-12-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0020_asignacionuniversal_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionuniversal',
            name='cavidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionuniversal',
            name='circuito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
