# Generated by Django 5.2.8 on 2025-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0021_alter_asignacionuniversal_cavidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionuniversal',
            name='tipo_sistema',
            field=models.CharField(default='Estandar', max_length=50),
        ),
    ]
