# Generated by Django 5.2.8 on 2025-12-12 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0022_asignacionuniversal_tipo_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lideradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lideradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lideradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lideradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
