# Generated by Django 5.2.8 on 2025-12-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0023_ordencho_lider_ordenmcm_lider_ordenprep_lider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionuniversal',
            name='detalles_json',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
