# Generated by Django 5.2.8 on 2025-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0024_asignacionuniversal_detalles_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensap',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
