# Generated by Django 5.2.8 on 2025-12-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0025_ordensap_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencho',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenmcm',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenprep',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentpm',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
