# Generated by Django 5.2.8 on 2025-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0026_alter_ordencho_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmcm',
            name='motivo_retorno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
