# Generated by Django 5.2.8 on 2025-12-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0027_ordenmcm_motivo_retorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmcm',
            name='observaciones_retorno',
            field=models.TextField(blank=True, null=True),
        ),
    ]
