# Generated by Django 5.2.8 on 2025-12-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0028_ordenmcm_observaciones_retorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensap',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
