# Generated by Django 5.2.8 on 2025-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0029_ordensap_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmcm',
            name='orden_retorno_ref',
            field=models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenmcm',
            name='motivo_retorno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
