# Generated by Django 5.2.8 on 2025-12-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0030_ordenmcm_orden_retorno_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moldes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='numerosdeparte',
            options={},
        ),
    ]
