# Generated by Django 5.2.8 on 2025-12-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0031_alter_maquinas_options_alter_moldes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moldes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='numerosdeparte',
            options={'managed': False},
        ),
    ]
