# Generated by Django 5.2.8 on 2025-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0032_alter_maquinas_options_alter_moldes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenmcm',
            name='orden_retorno_ref',
        ),
        migrations.RemoveField(
            model_name='ordensap',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='ordenmcm',
            name='motivo_retorno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
