# Generated by Django 5.2.8 on 2025-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0033_remove_ordenmcm_orden_retorno_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmcm',
            name='orden_retorno_ref',
            field=models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True),
        ),
    ]
