# Generated by Django 5.2.8 on 2025-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0034_ordenmcm_orden_retorno_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensap',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
