# Generated by Django 5.2.8 on 2025-12-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0035_ordensap_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='maquina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenmcm',
            name='maquina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='maquina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='maquina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
