# Generated by Django 5.2.8 on 2025-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moldeo', '0036_ordencho_maquina_ordenmcm_maquina_ordenprep_maquina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencho',
            name='motivo_retorno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordencho',
            name='observaciones_retorno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencho',
            name='orden_retorno_ref',
            field=models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='motivo_retorno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='observaciones_retorno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenprep',
            name='orden_retorno_ref',
            field=models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='motivo_retorno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='observaciones_retorno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentpm',
            name='orden_retorno_ref',
            field=models.CharField(blank=True, help_text='Número de la orden anterior que causó el retorno', max_length=50, null=True),
        ),
    ]
