<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eoats',
            fields=[
                ('id_eoat', models.AutoField(primary_key=True, serialize=False)),
                ('numero_eoat', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('locacion', models.CharField(blank=True, db_column='Locacion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'eoats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preventivos',
            fields=[
                ('id_preventivo', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('eoat', models.TextField(blank=True, null=True)),
                ('locacion', models.TextField(blank=True, null=True)),
                ('fecha_preventivo', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('numero_orden', models.CharField(blank=True, max_length=100, null=True)),
                ('antes', models.TextField(blank=True, null=True)),
                ('despues', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preventivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refacciones',
            fields=[
                ('id_refaccion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sap', models.CharField(blank=True, db_column='numero_SAP', max_length=100, null=True)),
                ('numero_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, null=True)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('locacion', models.CharField(blank=True, max_length=100, null=True)),
                ('disponible', models.IntegerField(blank=True, null=True)),
                ('cu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'refacciones',
                'managed': False,
            },
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-10-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eoats',
            fields=[
                ('id_eoat', models.AutoField(primary_key=True, serialize=False)),
                ('numero_eoat', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('locacion', models.CharField(blank=True, db_column='Locacion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'eoats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preventivos',
            fields=[
                ('id_preventivo', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('eoat', models.TextField(blank=True, null=True)),
                ('locacion', models.TextField(blank=True, null=True)),
                ('fecha_preventivo', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('numero_orden', models.CharField(blank=True, max_length=100, null=True)),
                ('antes', models.TextField(blank=True, null=True)),
                ('despues', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preventivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refacciones',
            fields=[
                ('id_refaccion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sap', models.CharField(blank=True, db_column='numero_SAP', max_length=100, null=True)),
                ('numero_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, null=True)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('locacion', models.CharField(blank=True, max_length=100, null=True)),
                ('disponible', models.IntegerField(blank=True, null=True)),
                ('cu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'refacciones',
                'managed': False,
            },
        ),
    ]
>>>>>>> dc13148 (Mi primera subida desde Windows)
