# Generated by Django 5.2.7 on 2025-11-07 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eoats',
            fields=[
                ('id_eoat', models.AutoField(primary_key=True, serialize=False)),
                ('numero_eoat', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('locacion', models.CharField(blank=True, db_column='Locacion', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], default='preparacion', max_length=20, null=True)),
            ],
            options={
                'db_table': 'eoats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preventivos',
            fields=[
                ('id_preventivo', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('eoat', models.TextField(blank=True, null=True)),
                ('locacion', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('fecha_preventivo', models.DateTimeField(auto_now_add=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('numero_orden', models.CharField(blank=True, max_length=100, null=True)),
                ('antes', models.TextField(blank=True, null=True)),
                ('despues', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preventivos',
                'ordering': ['-fecha_preventivo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refacciones',
            fields=[
                ('id_refaccion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sap', models.CharField(blank=True, db_column='numero_SAP', max_length=100, null=True)),
                ('numero_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, null=True)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('locacion', models.CharField(blank=True, max_length=100, null=True)),
                ('disponible', models.IntegerField(blank=True, null=True)),
                ('cu', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'refacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroPlanCargado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maquina', models.CharField(blank=True, max_length=100, null=True)),
                ('molde', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], default='preparacion', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
            ],
            options={
                'verbose_name': 'Registro de Plan Cargado',
                'verbose_name_plural': 'Registros de Planes Cargados',
                'ordering': ['maquina', 'molde'],
            },
        ),
        migrations.CreateModel(
            name='FotoEoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Eoats/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('eoat_fotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='EOATS.eoats')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('eoat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='EOATS.eoats')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
