<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-31 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible')], max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('eoat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='EOATS.eoats')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-10-31 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible')], max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('eoat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='EOATS.eoats')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
>>>>>>> dc13148 (Mi primera subida desde Windows)
