# Generated by Django 5.2.7 on 2025-11-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eoats',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='preventivos',
            options={'managed': False, 'ordering': ['-fecha_preventivo']},
        ),
        migrations.AlterModelOptions(
            name='refacciones',
            options={'managed': False},
        ),
    ]
