<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0002_movimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='estado_nuevo',
            field=models.CharField(choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], max_length=20),
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-10-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0002_movimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='estado_nuevo',
            field=models.CharField(choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], max_length=20),
        ),
    ]
>>>>>>> dc13148 (Mi primera subida desde Windows)
