# Generated by Django 5.2.7 on 2025-10-31 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0003_alter_movimientos_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivos',
            options={'managed': True, 'ordering': ['-fecha_preventivo']},
        ),
    ]
