# Generated by Django 5.2.7 on 2025-10-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0004_alter_preventivos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivos',
            name='fecha_preventivo',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
