<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0005_alter_preventivos_fecha_preventivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivos',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-11-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0005_alter_preventivos_fecha_preventivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivos',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
>>>>>>> dc13148 (Mi primera subida desde Windows)
