<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0006_preventivos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivos',
            options={'managed': False, 'ordering': ['-fecha_preventivo']},
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-11-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0006_preventivos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivos',
            options={'managed': False, 'ordering': ['-fecha_preventivo']},
        ),
    ]
>>>>>>> dc13148 (Mi primera subida desde Windows)
