<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0008_alter_preventivos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivos',
            name='tipo',
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-11-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0008_alter_preventivos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivos',
            name='tipo',
        ),
    ]
>>>>>>> dc13148 (Mi primera subida desde Windows)
