# Generated by Django 5.2.7 on 2025-11-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0009_remove_preventivos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivos',
            options={'managed': False, 'ordering': ['-fecha_preventivo']},
        ),
    ]
