# Generated by Django 5.2.7 on 2025-11-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0010_alter_preventivos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('eoat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='plan_mantenimiento', serialize=False, to='EOATS.eoats')),
                ('plan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plan Asignado')),
            ],
        ),
    ]
