# Generated by Django 5.2.7 on 2025-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0011_planmantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPlanCargado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maquina', models.CharField(blank=True, max_length=100, null=True)),
                ('molde', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
            ],
            options={
                'verbose_name': 'Registro de Plan Cargado',
                'verbose_name_plural': 'Registros de Planes Cargados',
                'ordering': ['maquina', 'molde'],
            },
        ),
        migrations.DeleteModel(
            name='PlanMantenimiento',
        ),
    ]
