# Generated by Django 5.2.7 on 2025-11-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0012_registroplancargado_delete_planmantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplancargado',
            name='status',
            field=models.CharField(choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], default='preparacion', max_length=20, verbose_name='Estado del Plan'),
        ),
    ]
