# Generated by Django 5.2.7 on 2025-11-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0013_registroplancargado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroplancargado',
            name='status',
            field=models.CharField(choices=[('produccion', 'En Producción'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('preparacion', 'Falta Preparacion')], default='preparacion', max_length=20),
        ),
        migrations.CreateModel(
            name='FotoEoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Eoats/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('eoat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='EOATS.eoats')),
            ],
        ),
    ]
