# Generated by Django 5.2.7 on 2025-11-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0014_alter_registroplancargado_status_fotoeoat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotoeoat',
            old_name='eoat',
            new_name='eoat_fotos',
        ),
    ]
