# Generated by Django 5.2.7 on 2025-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0015_rename_eoat_fotoeoat_eoat_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplancargado',
            name='tipo_plan',
            field=models.CharField(blank=True, default='PREP', max_length=10, null=True),
        ),
    ]
