# Generated by Django 5.2.8 on 2025-11-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0016_registroplancargado_tipo_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivos',
            options={'managed': True, 'ordering': ['-fecha_preventivo']},
        ),
    ]
