# Generated by Django 5.2.8 on 2025-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOATS', '0017_alter_preventivos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivos',
            name='hora_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='hora_paro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='maquina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='retorno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='retorno_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
